name: option-pricing
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - python-lsp-server
  - jupyterlab-lsp
  - yfinance
prefix: /home/jd/miniconda3/envs/option-pricing
